//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discord_2._0.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommunicationSoftwareDBEntities : DbContext
    {
        public CommunicationSoftwareDBEntities()
            : base("name=CommunicationSoftwareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
